### ISSUE TITLE
Depend on the numpy ABI used to build

### ISSUE THREAD

**Issue by jedbrown** [conda-forge/petsc4py-feedstock#6]
This run-time dependency is just on any version of numpy, not specifically on the ABI used to build petsc4py. I think that lack of specificity allowed [this problem](https://travis-ci.org/clawpack/pyclaw/jobs/308045283) wherein

    conda install -c conda-forge scipy=0.17.1

resulted in an older version of numpy, yielding

    RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

**Comment by dalcinl** [comment]
petsc4py is carefull enough to not depend on a specific NumPy ABI. However, I'm handling this the wrong way, as if petsc4py required the ABI of the NumPy used at building time. I'll push a patch in petsc4py/maint, then rebuild the conda-forge package with that patch (and just bump the build number).

**Comment by dalcinl** [comment]
Fixed after merging #7.
