### ISSUE TITLE
consider thinning supported matrix

### ISSUE THREAD

**Issue by minrk** [conda-forge/petsc4py-feedstock#96]
petsc4py and slepc4py now have 260 build variants because of:

- 2 mpi providers
- 2 scalar variants
- 6 Python versions
- 2 mac architectures
- 3 linux architectures
- 3 cuda variants on linux

This is causing rerenders to take at least 30 minutes, and time out on the bot, so I don't think any automated PRs are going to be made to these repos until something changes.

I think we should consider culling some of these to keep things manageable. Options include:

- drop Python 3.8 altogether (44 builds)
- only build cuda12 on Python >=3.11 (36 builds)
- only build cuda _at all_ on Python >=3.10 (48 builds) or 3.11 (72 builds)
- only keep 'complex' builds on Python >=3.10 (44 builds)

It would really be ideal if petsc4py didn't need to be aware of the cuda build variants at all, but I think @stefanozampini confirmed that it doesn't work that way (I can't find the reference anymore, though).

**Comment by stefanozampini** [comment]
Unfortunately it's not possible at the moment to use a petsc at runtime which is different than the build one

**Comment by dalcinl** [comment]
@stefanozampini Could you please remember me why we have 3 CUDA variants?

**Comment by stefanozampini** [comment]
The cuda variants are 11.8, 12.4 and nocuda

**Comment by minrk** [comment]
Looks like the rerender times are fixable upstream, and thinning the build matrix doesn't actually help rerender time. More info here: https://github.com/regro/cf-scripts/issues/2561 and a couple linked conda-build PRs.

So we should only bother thinning here if _build_ time is problematic.

**Comment by minrk** [comment]
closing this since rerender time is a lot more manageable now
